//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldenPet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Booking
    {
        public int id { get; set; }
        public Nullable<int> customerID { get; set; }
        public Nullable<int> serviceID { get; set; }
        public Nullable<System.DateTime> bookingDate { get; set; }
        public Nullable<System.DateTime> appoINTmentDate { get; set; }
        public Nullable<int> petNumber { get; set; }
        public string status { get; set; }
    
        public virtual tb_Customer tb_Customer { get; set; }
        public virtual tb_Service tb_Service { get; set; }
    }
}
