//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldenPet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_News
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_News()
        {
            this.tb_NewsImages = new HashSet<tb_NewsImages>();
        }
    
        public int NewsID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string Slug { get; set; }
        public string AuthorName { get; set; }
        public string CategoryName { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string Status { get; set; }
        public string Summary { get; set; }
        public string ThumbnailImageURL { get; set; }
        public string MetaTitle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_NewsImages> tb_NewsImages { get; set; }
    }
}
