//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldenPet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PackageFeature
    {
        public int id { get; set; }
        public Nullable<int> packageId { get; set; }
        public string featureName { get; set; }
        public Nullable<bool> isIncluded { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    
        public virtual tb_Package tb_Package { get; set; }
    }
}
