//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldenPet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Pet
    {
        public int id { get; set; }
        public string name { get; set; }
        public int customerId { get; set; }
    
        public virtual tb_Customer tb_Customer { get; set; }
    }
}
